def handle_unexpected_error(e):
    return {"code": "UNEXPECTED_ERROR"}, 500
